### ISSUE TITLE
lesson5

### ISSUE THREAD

**Issue by FoRuby** [FoRuby/qna#9]
`validates :best, uniqueness: { scope: :question_id }, if: :best?`
Валидаия, проверяющая что лучший ответ у текущего вопроса единственный.
Выстрелит если попытаемся создать или заапдейтить ответ в лучший.

Вот так было пару коммитов назад.
answer.rb
```
  def mark_as_best!
    transaction do
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end
```

answer_controller.rb
```
  def mark_best
    if current_user.author?(@answer.question) && !@answer.best?
      @answer.mark_as_best!
      flash.now[:success] = 'Best answer selected.'
    end
  end
```

В текущем конфиге во вьюхе есть возможность послать запрос на `mark_best` с правильным ответом, в итоге условие `!@answer.best?` стопает все на уровне контроллера.

Если посмотреть на метод mark_as_best!, то он сперва "обнуляет" все лучшие ответы,
а потом делает лучшим тот, на котором вызвали метод. В итоге валидация не выстрелит ни в первом, ни во втором случае. В первом [`update_all`](https://www.rubydoc.info/gems/activerecord/4.2.0/ActiveRecord%2FRelation:update_all) игнорит валидацию, а во втором просто не будет лучших ответов.

Более того, тонкий момент, если в текущем конфиге `mark_as_best!` будет вызван на лучшем
ответе, то `update!(best: true)` не сработает без релоада вопроса из БД. И в итоге все ответы будут обычными.

В общем я бы сделал вот так:
Экшен стопнет, если в него придет лучший ответ.
mark_as_best! сработает без краша на любом ответе.
answer.rb
```
  def mark_as_best!
    transaction do
      question.answers.update_all(best: false)
      reload.update!(best: true)
    end
  end
```
answer_controller.rb
```
  def mark_best
    if current_user.author?(@answer.question) && !@answer.best?
      @answer.mark_as_best!
      flash.now[:success] = 'Best answer selected.'
    end
  end
```
Объяни плиз как ты хотел увязать валидацию с `mark_as_best!`.

**Comment by aishek** [comment]
Кое-что упущено: `question.answers.update_all(best: false)` не обновит состояние объекта в памяти для `update!`, поэтому вызов этого метода всегда гарантирует пометку текущим целевого ответа.

Я бы к существующему решению ещё бы уникальный индекс в базу добавил, да и всё.
